[package]
name = "xml_struct_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
xml_struct = {path = "../xml_struct"}
proc-macro2 = "1"
quote = "1"
syn = "1"
